server:
  port: ${CUSTOM.SERVER.PORT:9080}

# Eureka Client Config
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

# Cloud Gateway Routes

spring:
  cloud:
    gateway:
      routes: 
        - id: user-service-data
          uri: lb://user-service
          #uri spring: application:name
          predicates:
            - Path=/api/user-service/**
          filters:
            - StripPrefix=2
            - MitocodeFilter=MitocodeKey,MitocodeValue
            #bloques //
            # - CustomFilterMitocode=MitocodeKey, MitocodeValue
            - AddRequestHeader=MitocodeKey, MitocodeValue
            - AddResponseHeader=MitocodeHeader, MitocodeHeaderValue
            # - AddRequestParameter=role, ROLE_USER
           
