server:
  #port: 8761
  port: ${CUSTOM.SERVER.PORT:9004}   
         
eureka:
  client:
    fetch-registry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


### Mongo database configuration
spring:
  data:
    mongodb:
      uri: mongodb://mitocode:mitocode@localhost:27017/mitocodedb?authSource=admin

#spring:
 # data:
  #  mongodb:
   #   host: localhost
    #  port: 27017
     # database: mitocode
      #username: mitocode
      ##uri: mongodb://mitocode:mitocode@localhost:27017
      #authentication-database: admin
    
encrypt:
  key: mitocode
